# Generated by Django 3.1 on 2020-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
