# Generated by Django 3.1 on 2020-09-04 14:33

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre autor')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('image', models.URLField(blank=True, default=None, null=True, verbose_name='Imagen')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True, verbose_name='color')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('image', models.URLField(blank=True, default=None, null=True, verbose_name='Imagen')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True, verbose_name='color')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('name', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('content', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('type', models.CharField(choices=[('B', 'Blog'), ('T', 'Tutorial')], max_length=1, verbose_name='tipo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
