# Generated by Django 3.1 on 2020-08-22 15:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200822_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Index')),
                ('state', models.BooleanField(default=True, verbose_name='Estado activo/inactivo')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('name', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('content', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Imagen')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
