# Generated by Django 3.1 on 2020-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombre autor'),
            preserve_default=False,
        ),
    ]
