# Generated by Django 3.1 on 2020-08-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('B', 'Blog'), ('T', 'Tutorial')], default=1, max_length=1, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
